# Generated by Django 5.0.1 on 2024-02-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name=''),
        ),
    ]
