# Generated by Django 4.2.1 on 2024-02-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_item_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name=''),
        ),
    ]
